tasks:
  - command: |
      curl -LsSf https://astral.sh/uv/install.sh | sh
      source $HOME/.local/bin/env
      uv sync --all-groups
  - command: |
      uv run pre-commit install
      uv run pre-commit install-hooks
