name: Upgrader

on:
  workflow_dispatch:
  schedule:
    - cron: "45 11 25 * *"

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: snok/install-poetry@v1
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "poetry"
      - run: rm poetry.lock
      - run: poetry lock -n
      - uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GH_PAT }}
          branch: update/poetry-upgrade
          title: "chore(deps): upgrade dependencies"
          commit-message: "chore(deps): upgrade dependencies"
